name = "HerbEvaluation"
uuid = "eb1bf938-813d-4942-ac0f-b4657a683e76"
authors = ["Jaap de Jong <jaapdejong15@gmail.com>", "Tilman Hinnerichs <t.r.hinnerichs@tudelft.nl>"]
version = "0.1.0"

[deps]
HerbData = "495a3ad3-8034-41b3-a087-aacf2fd71098"
HerbGrammar = "4ef9e186-2fe5-4b24-8de7-9f7291f24af7"
HerbCore = "2b23ba43-8213-43cb-b5ea-38c12b45bd45"

[compat]
julia = "1.8"
HerbData = "0.1.0"
HerbGrammar = "0.1.0"
HerbCore = "0.1.0"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
